name: CMake

on:
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install some packages
      run: sudo apt-get update && sudo apt-get install -y ninja-build

    - name: Install CMake 3.29
      run: |
        wget https://github.com/Kitware/CMake/releases/download/v3.29.9/cmake-3.29.9-linux-x86_64.sh
        chmod +x cmake-3.29.9-linux-x86_64.sh
        sudo ./cmake-3.29.9-linux-x86_64.sh --skip-license --prefix=/usr/local

    - name: Init repository
      run: git submodule update --init --recursive

    - name: Configure CMake
      run: ./gen_cmake.sh -o _build -${{env.BUILD_TYPE}} -c Ninja

    - name: Build
      # Build your program with the given configuration
      run: cmake --build _build

    - name: Test
      working-directory: ${{github.workspace}}/_build/tests/src
      run: ./Tests --gtest_filter=-MANUAL*
