name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Init repository
      run: git submodule update --init --recursive

    - name: Configure CMake
      run: ./gen_cmake.sh -o _build -${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build _build

    - name: Test
      working-directory: ${{github.workspace}}/_build/tests/src
      run: ./Tests --gtest_filter=-MANUAL*
