name: Format

on :
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev ]
    paths-ignore:
      - 'Docker'
      - '**/README.md'
      - '**/LICENCE'

jobs:
  fix-files:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install job dependencies
      run: |
        sudo apt-get update
        # To be updated with custom clang
        sudo apt-get install -y clang-format dos2unix 
    - name: Run fix_files
      run: |
        set +xe
        ./scripts/bashUtils/fix_files.sh 
    - name: Check for changes
      shell: bash
      run: |
        set +xe
        git diff --name-status --exit-code
        if [ $? -ne 0 ]; then
          echo "Code formatting issues found. Please run ./scripts/bashUtils/fix_files.sh and commit the changes."
          exit 1
        fi

  build-test-linux:
    uses: ./.github/workflows/linux.yml
    needs: fix-files
  build-test-windows:
    uses: ./.github/workflows/windows.yml
    needs: fix-files
  build-test-macos:
    uses: ./.github/workflows/macos.yml
    needs: fix-files

