name: Macos

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev ]
    paths-ignore:
      - 'Docker'
      - '**/README.md'
      - '**/LICENCE'

jobs:
  macos-build-and-test:
    strategy:
      fail-fast: false
      matrix:
        target: ["release","debug"]
        os: ["macos-13","macos-14"]

    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install job dependencies
      run : |
        brew install ninja
        brew install wget
        brew install bash
        brew install grep
        echo "$(brew --prefix grep)/libexec/gnubin" >> $GITHUB_PATH

    - name: Verify CMake
      run : |
        set -xe # exit on first error
        which cmake &> /dev/null 
        CMAKE_VERSION=$(cmake --version | awk '/version/ {print $3}')
        echo "Using cmake: ${CMAKE_VERSION}"

    - name: Configure CMake
      shell: bash
      run: |
        echo "Generating CMake for Target: ${{matrix.target}}" 
        ./gen_cmake.sh -o _build -${{matrix.target}} -c Ninja

    - name: Build
      # Build your program with the given configuration
      run: cmake --build _build

    - name: Test
      working-directory: ${{github.workspace}}/_build/tests/src
      shell: bash
      run: |
        test_cmd="./Tests --gtest_filter=-MANUAL*"
        if [ "${{matrix.target}}" = "debug" ]; then
          test_cmd="./Tests-d --gtest_filter=-MANUAL*"
        fi
        eval $test_cmd 
